name: sisfo_mobile
description: Sistem Informasi Akademik.

version: 1.0.2+4

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.13
  line_icons:
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_secure_storage: ^3.3.5
  http: ^0.12.2
  provider: ^4.3.2+3
  shimmer: ^1.1.2
  toast: ^0.1.5
  intl: ^0.16.1
  flushbar: ^1.10.4
  flutter_app_badger: ^1.3.0
  dio: ^3.0.10
  flutter_phoenix: ^0.1.0

  # Handle File
  flutter_pdfview: ^1.2.2
  path_provider: ^2.0.11
  # android_path_provider: ^0.3.0
  # permissions_plugin: ^1.1.4

  # firebase
  firebase_messaging: ^12.0.1
  plugin_platform_interface: ^2.0.2

  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
