name: sisfo_mobile
description: Sistem Informasi Akademik.

version: 1.0.4+6

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  collection: ^1.14.13
  line_icons:
  flutter_launcher_icons: ^0.10.0
  http: ^0.13.4
  provider: ^6.0.3
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  flushbar: ^1.10.4
  flutter_app_badger: ^1.3.0
  dio: ^4.0.6
  flutter_phoenix: ^1.0.0

  # Handle File
  flutter_pdfview: ^1.2.2
  path_provider: ^2.0.11
  # android_path_provider: ^0.3.0
  # permissions_plugin: ^1.1.4

  # firebase

  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  mime: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
